name: Bulid_go_helloword
on:
  pull_request:
    branches:
    - main
jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
    - name: Show system
      run: |
        echo -e "Total CPU cores\t: $(nproc)"
        cat /proc/cpuinfo | grep 'model name'
        apt update
        apt install go
    - name: Print Disk Space After
      run: df -h
